name: Build

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3

    - name: Set up JDK 1.8
      uses: actions/setup-java@v3
      with:
        distribution: 'zulu'
        java-version: 8
        java-package: jdk

    - name: Build
      env:
        SETARE_USERNAME: ${{ secrets.SETARE_USERNAME }}
        SETARE_PASSWORD: ${{ secrets.SETARE_PASSWORD }}
      run: |
        mkdir target
        timestamp=$(date -u +%Y%m%d-%H%M%S)
        echo "TIMESTAMP=${timestamp}" >>$GITHUB_ENV
        bash doall-github.sh target github ${timestamp}z ${timestamp} "${SETARE_USERNAME:-}" "${SETARE_PASSWORD:-}" DELETE-REPOSITORY-FILES-AS-WELL

    - uses: actions/upload-artifact@v3
      with:
        name: ndr-UBL-github-${{ env.TIMESTAMP }}z
        path: ./*
        #path: target/artefacts-UBL-2.3-github-${{ env.TIMESTAMP }}z/*
        #name: all-UBL-2.3-github-${{ env.TIMESTAMP }}z
        #path: ./*
